Repository utilForever/awesome-cafe, pull requests merged in 2022-03, with the labels that each got.

#2 ☕ 부산 - 노스커피 부산대 북문점 추가 및 오타 수정
  CONTRIBUTING.md
  README.md
Labels: size/M

#4 ☕️ 공그로트 추가
  README.md
Labels: size/S

#5 ☕ 카페드팽, 부산커피, 카페부케 추가
  README.md
Labels: size/M

#6 ☕ 이디야 강남대치점 / 엘피스 / 카페델로 추가
  README.md
Labels: size/M

#7 ☕ 요거프레소 한양대점 추가
  README.md
Labels: size/S

#1 ☕ 카페 아가미 추가
  README.md
Labels: size/S

#8 ☕ 목차 및 빈줄 추가
  README.md
Labels: size/XS

#9 ☕ 스타벅스 목포평화광장점 추가
  README.md
Labels: size/S

#10 ☕ 카페위드 추가
  README.md
Labels: size/S

#12 홍대, 홍입 주변 카페 추가
  README.md
Labels: size/M

#14 ☕ 카페드플로르 한경점 추가
  README.md
Labels: size/S

#16 ☕ 연희동 프로토콜 카페 추가
  README.md
Labels: size/S
