Repository utilForever/awesome-cafe, pull requests merged in 2022-05, with the labels that each got.

#22 ☕ 인천 송도 카페 추가
  README.md
Labels: size/M

#23 ☕ 더 카페 신방 추가
  README.md
Labels: size/S

#24 ☕ 대구 블라인드멜론 북문점, 대구 아뜰리에빈 경북대점 추가
  README.md
Labels: size/M

#25 ☕ 대전 할리스커피 대전충남대점 추가
  README.md
Labels: size/S

#26 잘못된 네이버 맵 링크 수정
  README.md
Labels: size/XS
